import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

function sanitize(str) {
  if (!str) return '';
  return String(str)
    .replace(/ă/g, 'a').replace(/Ă/g, 'A')
    .replace(/â/g, 'a').replace(/Â/g, 'A')
    .replace(/î/g, 'i').replace(/Î/g, 'I')
    .replace(/ș/g, 's').replace(/Ș/g, 'S')
    .replace(/ț/g, 't').replace(/Ț/g, 'T')
    .replace(/ş/g, 's').replace(/Ş/g, 'S')
    .replace(/ţ/g, 't').replace(/Ţ/g, 'T')
    .replace(/[^\x00-\x7F]/g, '');
}

export function generateInvoicePdf(invoice, clientName) {
  const doc = new jsPDF();
  const green = [45, 122, 45];
  const darkGreen = [26, 42, 26];
  const lightGray = [247, 248, 245];
  const borderGray = [236, 238, 230];

  // Header bar
  doc.setFillColor(...green);
  doc.rect(0, 0, 210, 18, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Client.Portal', 14, 12);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('INVOICE', 174, 12);

  // Invoice number + title
  doc.setTextColor(...darkGreen);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(`Invoice #${sanitize(invoice.number)}`, 14, 34);

  doc.setDrawColor(...borderGray);
  doc.setLineWidth(0.5);
  doc.line(14, 38, 196, 38);

  // Client + Date + Status
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 110, 100);
  doc.text('BILLED TO', 14, 47);
  doc.text('ISSUE DATE', 90, 47);
  doc.text('DUE DATE', 140, 47);
  doc.text('STATUS', 178, 47);

  doc.setTextColor(...darkGreen);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(sanitize(clientName), 14, 54);
  doc.text(
    invoice.createdAt
      ? new Date(invoice.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
      : new Date().toLocaleDateString('en-GB'),
    90, 54
  );
  doc.text(invoice.dueDate || '—', 140, 54);
  doc.text((invoice.status || 'draft').toUpperCase(), 178, 54);

  // Line items table
  const tableStartY = 66;
  autoTable(doc, {
    startY: tableStartY,
    head: [['Description', 'Qty', 'Unit Price', 'Amount']],
    body: (invoice.lines || []).map(line => [
      sanitize(line.description),
      String(line.quantity),
      `${Number(line.unitPrice).toFixed(2)} ${invoice.currency || 'EUR'}`,
      `${(line.quantity * line.unitPrice).toFixed(2)} ${invoice.currency || 'EUR'}`,
    ]),
    headStyles: {
      fillColor: green,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: darkGreen,
    },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { cellWidth: 20, halign: 'center' },
      2: { cellWidth: 35, halign: 'right' },
      3: { cellWidth: 35, halign: 'right' },
    },
    margin: { left: 10, right: 10 },
    tableWidth: 190,
    theme: 'grid',
  });

  // Totals
  const finalY = doc.lastAutoTable.finalY + 6;
  const rightEdge = 200;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 110, 100);
  doc.text('Subtotal:', rightEdge - 45, finalY, { align: 'right' });
  doc.setTextColor(...darkGreen);
  doc.text(`${Number(invoice.subtotal || 0).toFixed(2)} ${invoice.currency || 'EUR'}`, rightEdge, finalY, { align: 'right' });

  doc.setTextColor(100, 110, 100);
  doc.text(`Tax (${invoice.tax || 0}%):`, rightEdge - 45, finalY + 7, { align: 'right' });
  doc.setTextColor(...darkGreen);
  doc.text(`${Number(invoice.taxAmount || 0).toFixed(2)} ${invoice.currency || 'EUR'}`, rightEdge, finalY + 7, { align: 'right' });

  // Total box
  const totalBoxY = finalY + 10;
  const totalBoxHeight = 14;
  const totalBoxLeft = 110;
  const totalBoxWidth = rightEdge - totalBoxLeft;
  doc.setFillColor(...darkGreen);
  doc.roundedRect(totalBoxLeft, totalBoxY, totalBoxWidth, totalBoxHeight, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  const totalTextY = totalBoxY + totalBoxHeight / 2 + 3.5;
  doc.text('TOTAL', totalBoxLeft + 8, totalTextY);
  doc.text(`${Number(invoice.total || 0).toFixed(2)} ${invoice.currency || 'EUR'}`, rightEdge - 2, totalTextY, { align: 'right' });

  // Footer
  doc.setFillColor(...green);
  doc.rect(0, 282, 210, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Client.Portal', 14, 291);
  doc.text('Page 1 of 1', 180, 291);

  const fileName = `invoice-${sanitize(invoice.number)}.pdf`;
  doc.save(fileName);
}