import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

function sanitize(str) {
  if (!str) return '';
  return String(str)
    .replace(/ă/g, 'a').replace(/Ă/g, 'A')
    .replace(/â/g, 'a').replace(/Â/g, 'A')
    .replace(/î/g, 'i').replace(/Î/g, 'I')
    .replace(/ș/g, 's').replace(/Ș/g, 'S')
    .replace(/ț/g, 't').replace(/Ț/g, 'T')
    .replace(/ş/g, 's').replace(/Ş/g, 'S')
    .replace(/ţ/g, 't').replace(/Ţ/g, 'T')
    .replace(/[^\x00-\x7F]/g, '');
}

export function generateProposalPdf(proposal, clientName) {
  const doc = new jsPDF();
  const green = [45, 122, 45];
  const darkGreen = [26, 42, 26];
  const lightGray = [247, 248, 245];
  const borderGray = [236, 238, 230];

  // Header bar
  doc.setFillColor(...green);
  doc.rect(0, 0, 210, 18, 'F');

  // Logo
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Client.Portal', 14, 12);

  // Label
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('PROPOSAL', 170, 12);

  // Title
  doc.setTextColor(...darkGreen);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(sanitize(proposal.title), 14, 34);

  // Divider
  doc.setDrawColor(...borderGray);
  doc.setLineWidth(0.5);
  doc.line(14, 38, 196, 38);

  // Client + Date info
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 110, 100);

  doc.text('PREPARED FOR', 14, 47);
  doc.text('DATE', 100, 47);
  doc.text('STATUS', 160, 47);

  doc.setTextColor(...darkGreen);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(sanitize(clientName), 14, 54);
  doc.text(
    proposal.createdAt
      ? new Date(proposal.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
      : new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }),
    100, 54
  );
  doc.text(proposal.status?.toUpperCase() || 'DRAFT', 160, 54);

  // Description section
  if (proposal.description) {
    doc.setFillColor(...lightGray);
    doc.roundedRect(14, 62, 182, 28, 2, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(100, 110, 100);
    doc.text('PROJECT DESCRIPTION', 20, 70);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...darkGreen);
    const descLines = doc.splitTextToSize(sanitize(proposal.description), 170);
    doc.text(descLines.slice(0, 2), 20, 77);
  }

  // Pricing table
  const tableStartY = proposal.description ? 100 : 68;

  autoTable(doc, {
    startY: tableStartY,
    head: [['Description', 'Amount']],
    body: [
      [sanitize(proposal.title), `${proposal.price} ${proposal.currency || 'EUR'}`],
    ],
    foot: [['Total', `${proposal.price} ${proposal.currency || 'EUR'}`]],
    headStyles: {
      fillColor: green,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    footStyles: {
      fillColor: darkGreen,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 10,
      textColor: darkGreen,
    },
    columnStyles: {
      0: { cellWidth: 140 },
      1: { cellWidth: 42, halign: 'right' },
    },
    margin: { left: 14, right: 14 },
    theme: 'grid',
  });

  // Notes
  if (proposal.notes) {
    const notesY = doc.lastAutoTable.finalY + 12;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(100, 110, 100);
    doc.text('NOTES', 14, notesY);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...darkGreen);
    const noteLines = doc.splitTextToSize(sanitize(proposal.notes), 182);
    doc.text(noteLines, 14, notesY + 6);
  }

  // Valid until
  if (proposal.validUntil) {
    const validY = doc.lastAutoTable.finalY + (proposal.notes ? 30 : 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(100, 110, 100);
    doc.text(
      `This proposal is valid until: ${new Date(proposal.validUntil).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      14, validY
    );
  }

  // Footer
  doc.setFillColor(...green);
  doc.rect(0, 282, 210, 15, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Client.Portal', 14, 291);
  doc.text(`Page 1 of 1`, 180, 291);

  // Save
  const fileName = `proposal-${proposal.title.toLowerCase().replace(/\s+/g, '-').slice(0, 30)}.pdf`;
  doc.save(fileName);
}
